ToLetBdApp/Controllers/HouseOwnerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToLetBdEntity;

namespace ToLetBdApp.Controllers
{
    public class HouseOwnerController : Controller
    {
        //
        // GET: /HouseOwner/

        UserRepository userRepo = new UserRepository();
        UserTypeRepository userTypeRepo = new UserTypeRepository();
        PostRepository postRepo = new PostRepository();
        PostImageRepository imgRepo = new PostImageRepository();
        CommentRepository comRepo = new CommentRepository();

        public ActionResult Index()
        {
            var user = (User)Session["user"];
            ViewBag.totalPendingPost = postRepo.totalPendingPostByUserId(user.Id);
            ViewBag.totalPublishedPost = postRepo.totalPublishedPostByUserId(user.Id);
            return View();
        }

        public ActionResult Logout()
        {

            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Profile()
        {

            User admin = (User)Session["user"];

            return View();
        }

        private bool IsvalidContentType(string contentType)
        {
            return contentType.Equals("image/png") || contentType.Equals("image/jpg") || contentType.Equals("image/jpeg") || contentType.Equals("image/gif");
        }

        [HttpPost]
        public ActionResult Profile(User u)
        {

            HttpPostedFileBase photo = Request.Files["photo"];

            if (photo.ContentLength > 0)
            {

                if (!IsvalidContentType(photo.ContentType))
                {

                    TempData["msg"] = "Image is invalid!!";
                    return View();
                }
                else
                {
                    if (photo.ContentLength > 0)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(photo.FileName);
                        string extension = Path.GetExtension(photo.FileName);
                        fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        var path = Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                        photo.SaveAs(path);

                        if (ModelState.IsValid)
                        {


                            u.ImgPath = fileName;

                            userRepo.UpdateWithImg(u);
                            User us = userRepo.Get(u.Id);
                            Session["user"] = us;
                            User admin = (User)Session["user"];

                            TempData["msg"] = "Profile updated successfully!!";
                            return RedirectToAction("Profile");

                        }
                        else
                        {
                            ModelState.Values.SelectMany(v => v.Errors).ElementAt(0);
                            return View();
                        }



                    }
                    return View();
                }

            }
            else
            {

                if (ModelState.IsValid)
                {



                    userRepo.Update(u);
                    User us = userRepo.Get(u.Id);
                    Session["user"] = us;
                    User admin = (User)Session["user"];

                    TempData["msg"] = "Profile updated successfully!!";
                    return RedirectToAction("Profile");

                }
                else
                {
                    ModelState.Values.SelectMany(v => v.Errors).ElementAt(0);
                    return View();
                  
                }
            }



        }

        [HttpGet]
        public ActionResult Settings()
        {

            User admin = (User)Session["user"];
            ViewBag.admin = admin;
            return View();
        }

        [HttpPost]
        public ActionResult Settings(FormCollection form)
        {


            if (form["Newpassword"] == form["cpassword"])
            {
                if (String.IsNullOrEmpty(form["cpassword"]) || form["cpassword"].Length < 6)
                {
                    TempData["msg"] = "Password can't be empty or less than 6!!";
                    return RedirectToAction("Settings");
                }
                else
                {
                    userRepo.ChangePassById(Convert.ToInt32(form["Id"]), Convert.ToString(form["cpassword"]));
                    User u = userRepo.Get(Convert.ToInt32(form["Id"]));
                    Session["user"] = u;

                    TempData["msg"] = "Password changed successfully!!";
                    return RedirectToAction("Settings");
                }
            }
            else
            {
                TempData["msg"] = "Password doesn't matched!!";
                return RedirectToAction("Settings");
            }


        }

        [HttpGet]
        public ActionResult NewPost() {

            return View();
        }

        [HttpPost]
        public ActionResult NewPost(Post post, Picture picture)
        {
            var user = (User)Session["user"];
            PostRepository postRepo = new PostRepository();

            if (ModelState.IsValid) {

                if (picture.files.Count(file => file != null) > 0)
                {
                    post.PostDateTime = DateTime.Now;
                    post.UserId = user.Id;
                    post.Status = "Pending";
                    post.Views = 0;
                    postRepo.Insert(post);

                    foreach (var file in picture.files)
                    {
                        if (file.ContentLength > 0)
                        {

                            string fileName = Path.GetFileNameWithoutExtension(file.FileName);
                            string extension = Path.GetExtension(file.FileName);
                            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                            var path = Path.Combine(Server.MapPath("~/Content/PostImages"), fileName);
                            file.SaveAs(path);
                            PostImageRepository postImgRepo = new PostImageRepository();
                            PostImage pimg = new PostImage();
                            pimg.ImgPath = fileName;
                            pimg.PostId = post.Id;
                            postImgRepo.Insert(pimg);



                        }
                        else
                        {

                            TempData["msg"] = "Invalid Image!!";
                            return RedirectToAction("NewPost");

                        }
                    }
                    TempData["msg"] = "New Post Added!!";
                    return RedirectToAction("NewPost");
                }
                else {
                    TempData["msg"] = "Invalid Image!!";
                    return RedirectToAction("NewPost");
                }
                        
            }
            else
            {
                ModelState.Values.SelectMany(v => v.Errors).ElementAt(0);

                return View();
            }

           
          

           
        }

        public ActionResult CurrentPost()
        {
            User us = (User)Session["user"];

            List<Post> posts = postRepo.GetByUserId(us.Id);
            ViewBag.allposts = posts;

            return View();
        }

        public ActionResult DeletePost(int id)
        {
            postRepo.Delete(id);

            TempData["msg"] = "Post Deleted!!";
            return RedirectToAction("CurrentPost");
        }

        public ActionResult DesablePost(int id)
        {
            Post p = postRepo.Get(id);
            if (p.Status != "Pending")
            {

                postRepo.DesablePost(id);
                TempData["msg"] = "Post Desabled!!";
                return RedirectToAction("CurrentPost");
            }
            else {
                TempData["msg"] = "Post Already Desabled!!";
                return RedirectToAction("CurrentPost");
            }
            
        }

        [HttpGet]
        public ActionResult EditPost(int id)
        {
            Post p = postRepo.Get(id);

            ViewBag.post = p;
            return View();
        }


        [HttpPost]
        public ActionResult EditPost(Post post)
        {
            postRepo.EditPost(post);
            Post p = postRepo.Get(post.Id);
            ViewBag.post = p;

            TempData["msg"] = "Post Updated!!";
            return View();
        }

        [HttpGet]
        public ActionResult ViewPost(int id)
        {

            Post Post = postRepo.Get(id);
            ViewBag.post = Post;

            List<PostImage> postimg = imgRepo.GetAllImgByPostId(id);
            ViewBag.postImages = postimg;

            List<Comment> comments = comRepo.GetByPostId(id);
            ViewBag.com = comments;
            Session["comments"] = comments;

            List<User> alluser = userRepo.GetAll();
            ViewBag.alluser = alluser;

            return View();

        }

        [HttpPost]
        public ActionResult ViewPost(Comment comment)
        {

            if (Session["user"] != null)
            {

                var us = (User)Session["user"];
                comment.UserId = us.Id;
                comment.PostId = comment.PostId;
                comment.CommentDateTime = DateTime.Now;

                comRepo.Insert(comment);
                TempData["msg"] = "Comment added Successfully!!";
                return RedirectToAction("ViewPost");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }



        }

    }
}

ToLetBdApp/Views/HouseOwner/CurrentPost.cshtml
@model ToLetBdEntity.Post

@{
    Layout = "~/Views/Shared/_HouseOwnerLayout.cshtml";
}

<div class="col-md-9"> 

    <div class="panel panel-primary">
      <div class="panel-heading">Current Posts</div>
      <div class="panel-body">
          @if (TempData["msg"] != null)
            { 
            <p class="alert alert-danger">@TempData["msg"]</p>
            }

           @foreach(var post in ViewBag.allposts ){
          <div class="panel panel-success">
              <div class="panel-heading"><strong>@post.Title</strong></div>
              <div class="panel-body"> 
                 
                  

                  <div class="col-md-12"> 
                      <div class="row"> 
                          <div class="col-md-6"> 
                              <div class="row"> 
                                  <div class="col-md-6">
                                      <p style="width:100%;"><strong>No of Room: @post.NoOfRoom</strong></p>
                                   </div>
                                  <div class="col-md-6">
                                      <p style="width:100%;"><strong>House Rent: @post.RoomRent tk</strong></p>
                                   </div>
                              </div>
                          </div>
                          <div class="col-md-6"> 

                              <textarea style="width:100%;">@post.ShortDesc</textarea>
                          </div>
                      </div>
                  </div>
                  
                  <div class="col-md-12">
                      <div class="row"> 
                          <hr />

                          <div class="col-md-12"> 
                              <div class="col-md-8"><strong>Address: @post.Address</strong></div>
                              <div class="col-md-4"><strong>Status: @post.Status</strong></div>
                             
                          </div>
                          
                          <div class="col-md-12"> 
                              <hr />
                              <div class="col-md-offset-2 col-md-8"> 
                              
                                  <div class="col-md-3">
                                      <a href="/HouseOwner/DeletePost/@post.Id" style="text-decoration:none;">
                                          <button style="width:100%;" type="button" class="btn btn-danger">Delete</button>
                                      </a> 
                                  </div>
                                  <div class="col-md-3">
                                      <a href="/HouseOwner/EditPost/@post.Id" style="text-decoration:none;">
                                          <button style="width:100%;" type="button" class="btn btn-primary">Edit</button>
                                      </a> 
                                  </div>
                                  <div class="col-md-3">
                                      <a href="/HouseOwner/DesablePost/@post.Id" style="text-decoration:none;">
                                          <button style="width:100%;" type="button" class="btn btn-warning">Desable</button>
                                      </a> 
                                  </div>
                                  <div class="col-md-3">
                                      <a href="/HouseOwner/ViewPost/@post.Id" style="text-decoration:none;">
                                          <button style="width:100%;" type="button" class="btn btn-info">View</button>
                                      </a> 
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
                  
              </div>
          </div>
           }
      </div>
    </div>
</div>

ToLetBdApp/Views/HouseOwner/EditPost.cshtml
@model ToLetBdEntity.Post

@{
    ViewBag.Title = "EditPost";
    Layout = "~/Views/Shared/_HouseOwnerLayout.cshtml";
}



<div class="col-md-9"> 

    <div class="panel panel-primary">
      <div class="panel-heading">New Post</div>
      <div class="panel-body">
        @using (Html.BeginForm("EditPost", "HouseOwner", FormMethod.Post ))
        { 
             @Html.ValidationSummary(true)
            
            @Html.TextBoxFor(model => model.Id, new { @class = "form-control", PlaceHolder="Enter Post Title", Value =@ViewBag.post.Id.ToString(), type = "hidden" }) <br />
            @Html.Label("Title:")
            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", PlaceHolder="Enter Post Title", Value =@ViewBag.post.Title.ToString()}) <br />
             @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger"})
            @Html.Label("Description:")
            @Html.TextAreaFor(model => model.ShortDesc ,new { @class = "form-control ShortDesc", PlaceHolder="Enter Short Description"}) <br />
             @Html.ValidationMessageFor(model => model.ShortDesc, "", new { @class = "text-danger" })
            @Html.Label("Address")
            @Html.TextBoxFor(model => model.Address, new { @class = "form-control", PlaceHolder="Enter Address",Value =@ViewBag.post.Address.ToString() }) <br />
             @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })

            <script type="text/javascript">
                $(function () {
                    $("#ShortDesc").html("@ViewBag.post.ShortDesc.ToString()");
                });
            </script>
            
            <div class="row">
                <div class="col-md-12"> 

                    <div class="row"> 

                        <div class="col-md-6 container"> 
                            @Html.Label("Rent: ")
                            @Html.TextBoxFor(model => model.RoomRent, new { @class = "form-control", PlaceHolder="Enter Rent",Value =@ViewBag.post.RoomRent.ToString() }) <br />
                             @Html.ValidationMessageFor(model => model.RoomRent, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6"> 
                            @Html.Label("No Of Room: ")
                             @Html.TextBoxFor(model => model.NoOfRoom, new { @class = "form-control", PlaceHolder="Enter No Of Room",Value =@ViewBag.post.NoOfRoom.ToString()  }) <br />
                             @Html.ValidationMessageFor(model => model.NoOfRoom, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-12"> 

                    <div class="row"> 

                        
                       

                        
                    </div>
                </div>
            </div>
            <input type="submit" value="Update Post" class="btn btn-primary" /><br />
             if (TempData["msg"] != null)
              { 
                 <p class="alert alert-info">@TempData["msg"]</p>
              }
            
            
        }
      </div>
    </div>
</div>

ToLetBdApp/Views/HouseOwner/Index.cshtml
@model ToLetBdEntity.User

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_HouseOwnerLayout.cshtml";
}

<div class="col-md-9"> 

    <div class="panel panel-primary">
      <div class="panel-heading">Dashboard</div>
      <div class="panel-body">
          <div class="col-md-4">
                <div class="panel panel-primary">
            	    
				    <div class="panel-body">
					    <p style="text-align: center; font-size: 20px; font-weight: bold;">@ViewBag.totalPublishedPost</p>
				    </div>

                    <div class="panel-footer">
				        <div class="panel-title text-center"> Published Post </div>
				    </div>

			    </div>
           </div>

          <div class="col-md-4">
                <div class="panel panel-primary">
				    <div class="panel-body">
					    <p style="text-align: center; font-size: 20px; font-weight: bold;">@ViewBag.totalPendingPost</p>
				    </div>
                    <div class="panel-footer">
				        <div class="panel-title text-center"> Pending Post </div>
				    </div>
			    </div>
           </div>
      </div>
    </div>
</div>

ToLetBdApp/Views/HouseOwner/NewPost.cshtml
@model ToLetBdEntity.Post

@{
    Layout = "~/Views/Shared/_HouseOwnerLayout.cshtml";
    var user = (ToLetBdEntity.User)Session["user"];
}

<div class="col-md-9"> 

    <div class="panel panel-primary">
      <div class="panel-heading">New Post</div>
      <div class="panel-body">
        @using (Html.BeginForm("NewPost", "HouseOwner", FormMethod.Post, new {enctype="multipart/form-data" }))
        { 
             @Html.ValidationSummary(true)

            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", PlaceHolder="Enter Post Title" }) <br />
             @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            @Html.TextAreaFor(model => model.ShortDesc, new { @class = "form-control", PlaceHolder="Enter Short Description" }) <br />
             @Html.ValidationMessageFor(model => model.ShortDesc, "", new { @class = "text-danger" })
            @Html.TextBoxFor(model => model.Address, new { @class = "form-control", PlaceHolder="Enter Address" }) <br />
             @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            
            <div class="row">
                <div class="col-md-12"> 

                    <div class="row"> 

                        <div class="col-md-6 container"> 
                            @Html.TextBoxFor(model => model.RoomRent, new { @class = "form-control", PlaceHolder="Enter Rent" }) <br />
                             @Html.ValidationMessageFor(model => model.RoomRent, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6"> 
                             @Html.TextBoxFor(model => model.NoOfRoom, new { @class = "form-control", PlaceHolder="Enter No Of Room" }) <br />
                             @Html.ValidationMessageFor(model => model.NoOfRoom, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-12"> 

                    <div class="row"> 

                        
                       

                        <div class="col-md-6 container"> 
                            <label for="input-1">Upload Images</label>
                        </div>
                        <div class="col-md-6"> 
                             <input id="input-1" type="file" multiple="multiple"  name="files" class="file" data-show-upload="false"  data-show-preview="false" > <br />
                        </div>
                    </div>
                </div>
            </div>
            <input type="submit" value="Publish Post" class="btn btn-primary" /><br />
             if (TempData["msg"] != null)
              { 
                 <p class="alert alert-info">@TempData["msg"]</p>
              }
            
            
        }
      </div>
    </div>
</div>

ToLetBdApp/Views/HouseOwner/Profile.cshtml
@model ToLetBdEntity.User

@{
    
    Layout = "~/Views/Shared/_HouseOwnerLayout.cshtml";
    var user = (ToLetBdEntity.User)Session["user"];
}

<div class="col-md-9 col-sm-12">
	
	<div class="panel panel-info" >
        <div class="panel-heading">
            <div class="panel-title"> Profile </div>
        </div> 
	    <div class="panel-body">
	   		 
            <div class="row">
                 @using (Html.BeginForm("Profile", "HouseOwner", FormMethod.Post, new { enctype = "multipart/form-data" }))
                 { 
                               @Html.ValidationSummary(true)
                    <div class="col-md-4">
                        
                        @if (String.IsNullOrEmpty(user.ImgPath))
                        {
                             <img src="~/Content/Images/propic.jpg" class="img-rounded img-responsive" alt="Profile Photo"  />
                            
                        }else{
                           <img src="~/Content/Images/@user.ImgPath" class="img-rounded img-responsive" alt="Profile Photo"  />
                        }
                         
                         <input name="photo" id="photo" type="file"/>
                    </div>

                	<div class="col-md-8">
                        <div class="wrapper">
                                       
                             @Html.TextBoxFor(model => model.Id, new { @class = "form-control", Value = @user.Id.ToString(), type = "hidden" })
                             @Html.TextBoxFor(model => model.Password, new { @class = "form-control", Value = @user.Password.ToString(), type = "hidden" })
                             @Html.TextBoxFor(model => model.Name, new { @class = "form-control", Value = @user.Name.ToString(), PlaceHolder = "Name" }) <br />
                             @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                             @Html.TextBoxFor(model => model.Email, new { @class = "form-control", Value = @user.Email.ToString(), PlaceHolder = "Email" }) <br />
                             @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                             @Html.TextBoxFor(model => model.PhnNo, new { @class = "form-control", Value = @user.PhnNo, PlaceHolder = "Phone number" }) <br />
                             @Html.ValidationMessageFor(model => model.PhnNo, "", new { @class = "text-danger" })
                            

                            <button class="btn btn-sm btn-primary btn-block" type="submit">Update Profile</button>
                            
                             
                          
                              @if (TempData["msg"] != null)
                              { 
                                <p class="alert alert-info">@TempData["msg"]</p>
                              }
                            
                         
                         </div>
                	</div>
                 }
                

                
            </div>

		</div>
	
	</div>
</div>

ToLetBdApp/Views/HouseOwner/Settings.cshtml
@model ToLetBdEntity.User

@{

    Layout = "~/Views/Shared/_HouseOwnerLayout.cshtml";
}

<div class="col-md-9 col-sm-12">
	
	<div class="panel panel-info" >
        <div class="panel-heading">
            <div class="panel-title"> Settings </div>
        </div> 
	    <div class="panel-body">
	   		 
            <div class="row">

            	<div class="col-md-6">
                    <div class="wrapper">
                           
                           @using (Html.BeginForm("Settings", "HouseOwner", FormMethod.Post))
                           { 
                               @Html.ValidationSummary(true)
                           
                      

                            
                            @Html.PasswordFor(model => model.Id,new { @class = "form-control", value=@ViewBag.admin.Id, name="Id", type="hidden"}) <br />
                            @Html.PasswordFor(model => model.Password,new { @class = "form-control", value=@ViewBag.admin.Password }) <br />
                            <input type="password" class="form-control" name="Newpassword" placeholder="New Password"/> <br />
                            
                            <input type="password" class="form-control" name="cpassword" placeholder="Confirm Password"/> <br />
                            
                       

                            
                            <input type="submit" value="Change Password" class="btn btn-primary" /><br />
                           
                               if (TempData["msg"] != null) { 
                                <p class="alert alert-info">@TempData["msg"]</p>
                               }
                             
                        
                           }
                       
                    </div>
            	</div>
                
            </div>

		</div>
	
	</div>
</div>